### ISSUE TITLE
Error loading config - globally installed commitlint

### ISSUE THREAD

**Issue by skwde** [joshbolduc/vscode-commitlint#750]
Something similar is here https://github.com/joshbolduc/vscode-commitlint/issues/744.

I have `commitlint` installed globally. I can use it without issues on the command line.

I have following `commitlint.config.js` in my project directory:

```js
module.exports = {
    extends: ['@commitlint/config-conventional'],
};
```

I however get

```
Error loading config - commitlint
```

when I hoover the curly brackets in the lower right of the VSCode window.

Looking into `Output > comitlint`  I first see an error

```out
Uncaught exception: Error: Extension 'vscode.git' is not known or not activated
Error: Extension 'vscode.git' is not known or not activated
	at D.getActivatedExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:3504)
	at r.getExtensionExports (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:8710)
	at get exports [as exports] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:21813)
	at R (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:1:1488)
	at Ft (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:1:1859)
	at O (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:1:1941)
	at ut (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:1:2269)
	at re (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:6:1170)
	at ne (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:6:635)
	at Rt (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:6:1516)
	at S (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:6:1553)
	at ~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:6:1774
	at Array.forEach (<anonymous>)
	at ie (~/.vscode/extensions/joshbolduc.commitlint-2.4.6/dist/extension.js:6:1762)
	at Dn.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:13102)
	at Dn.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:12816)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10913
	at async p.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6206)
	at async p.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6169)
	at async p.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:5626)

loading @commitlint/parse dynamically via ~/.config/nvm/versions/node/v18.12.1/lib/node_modules/@commitlint/cli/node_modules/@commitlint/parse/lib/index.js
loading @commitlint/load dynamically via ~/.config/nvm/versions/node/v18.12.1/lib/node_modules/@commitlint/cli/node_modules/@commitlint/load/lib/load.js
Load config error stack:
Error: Cannot find module "@commitlint/config-conventional" from "~/src/docs"
```

Since the error starts with `vscode.git` extension not known, I have `eamodio.gitlens` installed but I cannot find information that it disables `vscode.git`?! Also the error appears when I disable `eamodio.gitlens`

The same is true when I set 

```json
"commitlint.preferBundledLibraries": true,
```

or

```json
"commitlint.globalLibraryPath": "~/.config/nvm/versions/node/v18.12.1/lib",
```

or

```json
"commitlint.globalNodePath": "~/.config/nvm/versions/node/v18.12.1/bin/node",
```

In my `settings.json`.

Note, I am on MacOS and recent VSCode version.

**Comment by joshbolduc** [comment]
Does this repo for you with v2.4.2 of the extension? In retrospect, c1ba4d04306e228ddcf4a006883d7296562fc449 looks suspicious.

**Comment by skwde** [comment]
No, the problem is not present in v2.4.2.
