### ISSUE TITLE
v2.5.0 Uncaught exception

### ISSUE THREAD

**Issue by chris3ware** [joshbolduc/vscode-commitlint#755]
Hi, I just noticed that v2.5.0 was not highlighting invalid commit messages. I rolled back to version v2.4.7 and the extension is working as expected.

Version v2.5.0 produces the following output when I run `git commit`

```
loading bundled version of @commitlint/parse as fallback
Uncaught exception: TypeError: Invalid host defined options
TypeError: Invalid host defined options
	at xt (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:1:3093)
	at j (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:1:3537)
	at bt (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:1:3774)
	at Ot (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:4:1273)
	at se (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:6:1234)
	at async re (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:6:629)
	at async It (/Users/chris/.vscode/extensions/joshbolduc.commitlint-2.5.0/dist/extension.js:6:1510)
```

I am using macOS Sonoma 14.3.1 and VSCode 1.87.0

**Comment by joshbolduc** [comment]
Bummer. It looks like an issue with VS Code's handling of ESM imports. Weirdly I can't reproduce any of this using the extension development host, only when I run the extension in a normal VS Code instance without a debugger attached.

It looks like the prettier extension dealt with something similar last year and got around it by using worker threads; I'll probably have to do something similar.

For now, I'll revert and reopen #753, because being broken for v19 users is preferable to being broken for everyone.

Thanks for the report!
